export interface IExtrasCalculateResult {
  menuExtraID: number,
  menuExtraName: string,
  menuExtraCode: string,
  qty: number,
  price: number,
  statusID: number,
  discount: number,
  otherTax: number,
  vat: number,
  otherTaxOnVat: number,
  inclusivePrice: string,
  otherTaxValue: number,
  vatValue: number,
  total: number,
}

export interface IPackagesCalculateResult {
  menuCategoryID: number,
  menuCategoryDetailID: number,
  menuID: number,
  menuGroupID: number,
  menuName: string,
  menuCode: string,
  menuShortName: string,
  qty: number,
  originalPrice: number,
  originalInclusivePrice: string,
  price: number,
  notes: string,
  packages: IPackagesCalculateResult[],
  extras: IExtrasCalculateResult[],
  statusID: number,
  salesType: string,
  menuTypeID: number,
  createdBy: string,
  discount: number,
  otherTax: number,
  vat: number,
  otherTaxOnVat: number,
  otherTaxValue: number,
  vatValue: number,
  total: number,
  inclusivePrice: string,
}

export interface ISalesMenusCalculateResult {
  menuCategoryID: number,
  menuCategoryDetailID: number,
  menuID: number,
  menuGroupID: number,
  menuName: string,
  menuCode: string,
  menuShortName: string,
  customMenuName: string,
  originalPrice: string,
  originalInclusivePrice: number,
  price: number,
  sellPrice: string,
  qty: number,
  notes: string,
  packages: IPackagesCalculateResult[],
  extras: IExtrasCalculateResult[],
  statusID: number,
  salesType: string,
  menuTypeID: number,
  createdBy: string,
  inclusivePrice: string,
  discountValue: number,
  discount: number,
  otherTax: number,
  vat: number,
  otherTaxOnVat: number,
  otherTaxValue: number,
  vatValue: number,
  total: number,
}

export interface ICalculateTotalResult {
  deliveryCourier: string,
  distance: number,
  distanceText: string,
  deliveryCost: number,
  originalDeliveryCost: number,
  deliveryCostMessage: string | null,
  promotionCode: string,
  promotionDiscount: number,
  subtotal: number,
  pb1: number,
  additionalTax: number,
  orderFee: number,
  grandTotal: number,
  roundingTotal: number,
  discountTotal: number,
  discountTotalDisplay: number,
  minimumSubtotal: number,
  flagMinimumSubtotal: boolean,
  voucherDiscountTotal: number,
  orderVoucherUsage: string[],
  voucherTotal: number,
  vouchers: string[],
  flagInclusive: boolean,
  salesMenus: ISalesMenusCalculateResult[],
}